### ISSUE TITLE
Image markdown styling via alt-tag: Syntax and Effectiveness

### ISSUE THREAD

**Issue by broesmel** [scout-ch/thilo#115]
The current alt-tag image styling needs to be more user friendly and readable. 

Current example: `[alt: test-image, size: 150pxx150px]`

I think mirroring CSS style attributes would be an improvement:

`[caption: test-image; width: 150px; height: 150px;]`

Furthermore, in the current setup, the style tags are added to a parent `div` created around the `img`, which means it will not change the image ratio / the height is ignored when smaller than the width * ratio. This I take is explicitly requested when adding both width and height tags.

**Comment by broesmel** [comment]
Done. Image styling and caption can now be added through the images `alt` attribute like so:
`[caption: test-image; width: 150px; height: 150px;]`, independently of the order of the added tags and any leading or trailing white space. Any units work for the width and height tags (and other valid css style tags can be used as well).

caveats:
- all tags must be specified as `tag: value;` with a colon to distinguish and semicolon to terminate.
- existing images need to be ported to this format

**Comment by jimmylevell** [comment]
Implemented by @broesmel
