### ISSUE TITLE
darkmode 

### ISSUE THREAD

**Issue by aladwani** [scout-ch/thilo#117]
Integrate dark mode possibility and theme (white and dark) changer

**Comment by broesmel** [comment]
The dark mode was implemented. 

Still open: 
- [ ] ensure the colors supplied for all pages are good for both light and dark mode. 

Alternatively, it would be possible to choose one color for the light version and one for the dark version, and simply highlight everything using the same color.

Thanks1

**Comment by jimmylevell** [comment]
@broesmel : how can I help in this issue?
