### ISSUE TITLE
Floating UI rework

### ISSUE THREAD

**Issue by bodobraegger** [scout-ch/thilo#120]
- [x] header always collapsible
- [x] button instead of header
- [x] sidebar floating
- [x] floating footer with max width, subtle
- [x] floating list buttons, use chapter icons
- [x] content inside the floating is flat
- [ ] color and highlight color generation
- [x] colorize bullet points
- [x] colorized table lines
- [x] any highlighted text should be secondary color
- [x] figure out search button / styling - look github for inspo, no border, no shadow, content 'Kapitel durchsuchen'...
- [x] style scrollbars consistenly
- [x] move footer largely inside the sidebar, except for page next buttons

**Comment by aladwani** [comment]
<img width="566" alt="image" src="https://github.com/scout-ch/thilo/assets/6897078/90a0e4e1-0a6c-4886-9c09-0788a5e3b106">

**Comment by aladwani** [comment]
<img width="550" alt="image" src="https://github.com/scout-ch/thilo/assets/6897078/cb56f28c-ed72-4d7f-95fd-45beac6cccf6">

**Comment by jimmylevell** [comment]
>  color and highlight color generati

Colors need additional consideration. At the moment need to be chosen manually and provided by strapi. @aladwani
