### ISSUE TITLE
Migrate away from CRA and CRACO towards a supported framework

### ISSUE THREAD

**Issue by bodobraegger** [scout-ch/thilo#133]
Or configure react ourselves

CRA support was officially dropped as of 2023.

**Comment by jimmylevell** [comment]
How much work is it to configure react by ourselves compared of using another framework?
As much standardization as possible is preferred.

**Comment by broesmel** [comment]
I will evaluate this briefly before deciding for which way to go.

Ejecting and configuring ourselves will not be a lot of work but might cause complications later on, whereas using a framework will be more work upfront but require less maintenance.

Perhaps  @jimmylevell could inquire with a react expert?

Thanks!

**Comment by jimmylevell** [comment]
@diegosteiner : do you have experience or insight within this topic? 

The goal is to replace react-scripts (based on: https://dev.to/ag2byte/create-react-app-is-officially-dead-h7o) either with
- next.js
- or "plain" react
- vite (reference project: https://github.com/Azure-Samples/azure-search-openai-demo/tree/main/app/frontend)
- other alternatives 

@broesmel : feel free to provide additional insights to the topic.
