### ISSUE TITLE
No content shown when browser language is "en"

### ISSUE THREAD

**Issue by carlobeltrame** [scout-ch/thilo#135]
My web browser is set to English. When I load https://scout-ch.github.io/thilo, I get the following page:

![Screenshot from 2023-09-09 12-21-04](https://github.com/scout-ch/thilo/assets/7566995/412cffa7-be57-4843-9a40-11e8cc373c6e)

I would imagine the same happens for any language other than the available de, fr or it. In the website menu, none of the available languages is selected. Thilo probably needs some proper fallback logic in case the browser language is not available as application language.

(Note: Once I select a locale in the website menu, I automatically get back to this locale on later reloads. But the problem can be reproduced in a new private window.)

**Comment by carlobeltrame** [comment]
The problem still persists for me, and I don't see any code changes related to this topic. I am not redirected to any of the available languages. Are you sure your change has taken effect?

**Comment by jimmylevell** [comment]
@broesmel could you please have a look at this in the next iteration?

**Comment by broesmel** [comment]
Thanks a lot @carlobeltrame! The change was indeed pushed to development branch. Added it to main, this should be fixed.

**Comment by carlobeltrame** [comment]
Thanks, will test soon!

**Comment by carlobeltrame** [comment]
I can confirm it works now.

**Comment by broesmel** [comment]
Thanks a lot!
