### ISSUE TITLE
Refactoring of code base & developer documentation

### ISSUE THREAD

**Issue by aladwani** [scout-ch/thilo#62]
Refactor the code of the app to make it more clear. Increase reusability and incode documentation (comments)

**Comment by jimmylevell** [comment]
@broesmel : could you point out which commit you mean where I have added dependencies to the wrong section? As I went through my latest commits and only saw that I have added "serve" https://github.com/scout-ch/thilo/commit/cd45a63ef9fc027b82b827abba76c306b232e767#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519. 

Just that I can fix the wrong assignment. Thank you for pointing out! :)

**Comment by broesmel** [comment]
Hello! Sorry for the delay in answering. 

Using "serve" as an example - which is not required in our production server as far as I know. When adding dependencies just used by developers, you can save them globally `npm install -g <package_name>` and leave them out of the project. Or, if you they are necessary for the development workflow, you can add them to the devDependencies `npm install <package-name> --save-dev`.
This avoids  get compilation errors in case of dependency conflicts and so on.

Thanks!

**Comment by broesmel** [comment]
@aladwani 

Is the ['tasks'](https://github.com/scout-ch/thilo/blob/master/src/components/Task.tsx) functionality as ported over the hering project relevant for thilo? 



Otherwise I would go ahead and remove it and refactor it out.

**Comment by broesmel** [comment]
I consider this to be mainly done, now waiting for the content to see if everything holds up. The code has some comments now and a dev guide can be created once we are nearing release.

**Comment by jimmylevell** [comment]
Status of open tasks

- [ ] Clear dev dependencies

**Comment by broesmel** [comment]
I think (most of) the dev dependencies need to remain in the project to facilitate development. They are never going into the production code so this should not be too big of an issue.

**Comment by broesmel** [comment]
Yes, exactly. Now, only production relevant dependencies are used in the build process, and developer dependencies are used during local development.
