### ISSUE TITLE
How to search in the current setup

### ISSUE THREAD

**Issue by aladwani** [scout-ch/thilo#68]
Let's meet in January and fix the search field to query the data that comes from the json files that we get from the server.

**Comment by broesmel** [comment]
Sync component now uses propagated section data form initial page load

**Comment by jimmylevell** [comment]
Status of open tasks

- [x] Search: Search now works with fetched content (e.g. https://scout-ch.github.io/thilo/#/search?keyword=samariter)

**Comment by jimmylevell** [comment]
Please remove markdown details in the result view. 

![image](https://github.com/scout-ch/thilo/assets/14213673/4433ebd2-d79e-49ca-9fff-2a999280d2c7)

**Comment by broesmel** [comment]
This is not trivial, requires an efficient markdown - to unstructured text parsing function or providing this data from the strapi. Currently we only handle markdown - to - html. I tried briefly using prebuilt packages but none were satisfactory as of yet.
