### ISSUE TITLE
Integrate Analytics

### ISSUE THREAD

**Issue by jimmylevell** [scout-ch/thilo#86]
Requirements
- who access (unique users) from where the app?

Goal
- to measure the usage of the app and the coverage of the app

**Comment by jimmylevell** [comment]
https://blog.saeloun.com/2022/02/17/how-to-integrate-react-app-with-google-analytics.html

**Comment by jimmylevell** [comment]
PBS is trying to move away from Google Analytics and is considering https://plausible.io/.

**Comment by jimmylevell** [comment]
Decision: 

- Google Analytics will not be used based on privacy concerns
- an open source alternative should be evaluated

**Comment by jimmylevell** [comment]
@Michael-Schaer : have you implemented plausible yet? Do we have a running instance we could integrate thilo too?

**Comment by Michael-Schaer** [comment]
I sent you the snipped for adding Plausible to scout-ch.github.io/thilo. If you want to switch domain first, let me know. (e.g. thilo.scout.ch oder thilo.pbs.ch)

**Comment by jimmylevell** [comment]
@bodobraegger : I have sent you the required information, could you please integrate it in the frontend? 
Let me know if I can help you in any way

**Comment by bodobraegger** [comment]
Sorry, I missed your email! I have added it to the pages' head. Thanks a lot!
